title: Illia Kibalnyi | Software Engineer - Curriculum Vitae
email: illia.kibalnyi@gmail.com
description: >-
  The Curriculum Vitae of Illia Kibalnyi.
domain: ikibalnyi.github.io
phone: +41747028329
google_analytics: UA-141571444-1

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
