title: Illia Kibalnyi | Software Engineer - Curriculum Vitae
description: >-
  The Curriculum Vitae of Illia Kibalnyi.
google_analytics: UA-141571444-1

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

exclude:
  - .idea
  - .gitignore

theme: jekyll-theme-minimal
